- name: 'Add repo PHP 5.5 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php5'

- name: 'PHP + libraries installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-intl
    - php5-json
    - php5-curl
    - php5-mcrypt
    - php5-gd
    - php5-pgsql
    - php5-mysql
    - php-pear
  tags: php

- name: Enable PHP modules
  shell: php5enmod {{ item }}
  with_items:
    - mcrypt
  tags: php

- name: Configure PHP settings
  template: src=php.ini dest=/etc/php5/apache2/conf.d/custom.ini
  tags: php

- name: Chown PHP sessions dir
  file: path=/var/lib/php5 state=directory owner={{ username }} group={{ username }}
  tags: php